### ISSUE TITLE
Installation in Homebridge 

### ISSUE THREAD

**Issue by Trunks1982** [cgHome/homebridge-digitalSTROM#3]
Hallo ich wollte Digitalstrom für Homebridge installieren aber es klappt nicht.
Dieses wird mir bei der Installation ausgespuckt.
Wie bekommt man es hin?

<img width="804" alt="Bildschirmfoto 2021-09-05 um 15 22 36" src="https://user-images.githubusercontent.com/62701386/132128507-f7e0e37c-5c09-4628-8edd-f9032e751f2d.png">

**Comment by cgHome** [comment]
Tag

Folgendes, nachdem sich mein damaliger Auftraggeber geweigert hatte mich zu bezahlen, habe ich die Homebridge-DigitalStrom Wartung und Weiterentwicklung eingestellt und mein Test-Gerät zurückgegeben. 

Zwischenzeitlich hat sich jedoch das API geädert und man müsste die App nochmals überarbeiten, um sie auf den neusten Stand zu bringen. Falls Du jemanden findest, der das für Dich erledigen könnte, kannst er gerne meine App „forken“ und die Änderungen machen.

Ich habe zwischenzeitlich meinen Fokus Richtung „Cloud free“ Smart Home (https://homey.app/) gelegt, so nach dem Motto „my home is not on cloud". Aber auch bei "homey" gibt es keine Anbindung und es wird in absehbarer Zeit, soweit mir bekannt ist auch keine geben, denn die DigitalStrom-Anbindung ist nicht ganz trivial und zeitaufwendig !😏! Also wenn „man" einen (oder mehrere) Sponsor findet, der auch ein Test-Gerät zur Verfügung stellen kann, dann könnte man sicher darüber diskutieren.

Also Sorry, dass ich Dir nicht weiterhelfen konnte.

Gruss

Chris
